@startuml

package logica {


    class Carta {
    - valor: string
    - pinta: string
    + _init_(valor: string, pinta: string)
    + dar_valor(): int
    + mostrar(): string
}

    class Mazo {
    - Cartas: list
    + _init_(jugador = False)
    + dar_valor(): int
    + tiene_as(): bool
    + dar_carta(): Carta
    + agregar_carta(carta): None
    + mostrar_carta(todas = False): None
}

    class Juego {
    - Mazo: mazo
    - casa: mazo
    - jugador: mazo
    + _init_()
    + iniciar_juego(): None
    + mostrar_juego(): None
    + Plant_casa_juego(): None
    + Plan_juego(): None
    }

}


Principal -- Juego
Juego o-- Mazo
Mazo o-- Carta
@enduml